# Generated by Django 4.1.7 on 2023-04-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'verbose_name': 'drug', 'verbose_name_plural': 'drugs'},
        ),
    ]
