# Generated by Django 4.1.7 on 2023-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
